language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.4.0
  - 2.5.3
  - 2.6.0
  - jruby

sudo: false

env:
  - OLD_RAILS=1

script: bundle exec rake

bundler_args: --without docs release repl

matrix:
  include:
    - rvm: 2.4.0
      env: NEW_RAILS=1
  exclude:
    - rvm: 2.4.0
      env: OLD_RAILS=1

